config/routes.rb
Rails.application.routes.draw do
  	root "puzzles#index"
	post "puzzles/validate_code/:id" => "puzzles#validate_code", as: "validate_puzzle"
	get "users/brew_puzzles" => "users#user_puzzles", as: "brew_puzzles"

	resources :sessions
	resources :users
	resources :puzzles do
		resources :forums
	end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/forum.rb
class Forum < ApplicationRecord
	belongs_to :user
	belongs_to :puzzle

	validates :content, presence: true, length: { in: 4..255 }
end

app/models/puzzle.rb
class Puzzle < ApplicationRecord
	belongs_to :user

	has_many :user_puzzles, dependent: :destroy
	has_many :users, through: :user_puzzles
	has_many :forums

	serialize :test_cases, Array
	serialize :expected_outputs, Array

	validates :title, presence: true
	validates :difficulty, presence: true
	validates :description, presence: true
	validates :function, presence: true
	validates :test_cases, presence: true
	validates :expected_outputs, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  	has_secure_password

	has_many :puzzles, dependent: :destroy
	has_many :user_puzzles, dependent: :destroy
	
	before_validation :downcase_email

	validates :email, presence:true, on: :login

	validates :username, presence: true, length: { in: 4..45 }, on: [:create, :update]
	validates :email, presence: true, uniqueness: true, length: { in: 5..45 }, email: true, on: [:create, :update]
	validates :password, presence: true, comparison: { equal_to: :password_confirmation }, length: { in: 4..45 }, on: [:create, :update]
	validates :password_confirmation, presence: true, length: { in: 4..45 }, on: [:create, :update]

	def downcase_email
		self.email.downcase! if email.present?
	end
end

app/models/user_puzzle.rb
class UserPuzzle < ApplicationRecord
	belongs_to :user
	belongs_to :puzzle

	serialize :playback, Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def current_user
		User.find(session[:user_id]) if session[:user_id]
	end

	def check_user
		redirect_to new_session_path unless current_user
	end
	helper_method :current_user
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
	def create
		@puzzle = Puzzle.find(params[:puzzle_id])
		@post = @puzzle.forums.new(forum_params)
		@post.user_id = current_user.id

		if @post.valid?
			@post.save
			@html = render_to_string(partial: "/puzzles/partials/post")
		else
			@errors = @post.errors.full_messages
		end
		
		respond_to do |format|
			format.json {render json: { post: @post, errors: @errors, html: @html }}
		end
	end

	def update
		@puzzle = Puzzle.find(params[:puzzle_id])
		@post = @puzzle.forums.find(params[:id])
		@post.update(forum_params)
		
		@errors = @post.errors.full_messages unless @post.valid?
		
		respond_to do |format|
			format.json {render json: { errors: @errors }}
		end
	end

	def destroy
		@puzzle = Puzzle.find(params[:puzzle_id])
		@post = @puzzle.forums.find(params[:id])
		@post.destroy
	end

	private
	def forum_params
		params.require(:forum).permit(:content)
	end
end

app/controllers/puzzles_controller.rb
class PuzzlesController < ApplicationController
	before_action :check_user

	def index
		@puzzles = 	Puzzle.all
		@user_puzzles = current_user.user_puzzles.index_by(&:puzzle_id)
	end

	def new
		@puzzle = Puzzle.new
		@difficulty = ["Easy", "Medium", "Hard"]
	end

	def edit
		@puzzle = Puzzle.find(params[:id])
		@difficulty = ["Easy", "Medium", "Hard"]
	end

	def destroy
		Puzzle.find(params[:id]).destroy
		redirect_to(brew_puzzles_path)
	end

	def show
		@puzzle = Puzzle.find(params[:id])
		@completed_puzzles = UserPuzzle.where(puzzle_id: params[:id], completed: true)
		@new_post = Forum.new
		@puzzle_posts = @puzzle.forums
		
		if params[:result]
			@result = params[:result]
		end
		
		gon.completed_puzzles = @completed_puzzles
	end

	def create
		@puzzle = current_user.puzzles.create(puzzle_params)
		if @puzzle.valid?
			redirect_to brew_puzzles_path 
		else
			@difficulty = ["Easy", "Medium", "Hard"]
			flash[:errors] = @puzzle.errors.full_messages
			redirect_to new_puzzle_path
		end
	end

	def update
		@puzzle = current_user.puzzles.find(params[:id])
		@puzzle.update(puzzle_params)

		if @puzzle.valid?
			redirect_to puzzles_path
		else
			@difficulty = ["Easy", "Medium", "Hard"]
			flash[:errors] = @puzzle.errors.full_messages
			redirect_to edit_puzzle_path(@puzzle)
		end
	end

	def validate_code
		#get puzzle data and prep variables
		@puzzle = Puzzle.find(params[:id])
		@completed = false;
		@console = [];
		@status = [];

		#extract form data from parameters
		form_data = Rack::Utils.parse_nested_query(params[:form])
		code = form_data['code']

		@puzzle.test_cases.each_with_index do |test_case, index|
			# Generate function to be used for testing
			generate_function = "def #{@puzzle.function}\n"
			generate_function += code+"\n"
			generate_function += "end\n"
			generate_function += test_case
			
			# Capture output of eval and puts statements in a string buffer
			output_buffer = StringIO.new
			$stdout = output_buffer
			
			#evaluate function generated
			begin
				@result = eval(generate_function)
				if @result.to_s == @puzzle.expected_outputs[index]
					@status << "pass"
				else
					@status << "fail"
				end
				
				# Reset stdout back to STDOUT
				$stdout = STDOUT
				@console << "\n"+output_buffer.string

			rescue SyntaxError, StandardError => e
				@error = "fail\nError: #{e.message}"
			end
		end

		#if user passes all test cases add user to user_puzzles
		if @status.all? { |status| status == "pass" }
			@completed = true;
		
			unless UserPuzzle.exists?(user_id: current_user.id, puzzle_id: params[:id], completed: true)				
				playback = JSON.parse(params[:playback])
				@completed_puzzle = UserPuzzle.create(user_id: current_user.id, puzzle_id: params[:id], completed: true, playback: playback)	
				@html = render_to_string(partial: "/puzzles/partials/playback")
			end
		end

		# Include captured output in result
		respond_to do |format|
			
			format.json {render json: { console: @console, status: @status, completed: @completed, error: @error, completed_puzzle: @completed_puzzle, html: @html }}
		end
	end

	private
	def puzzle_params
		params.require(:puzzle).permit(:user_id, :title, :difficulty, :description, :function, test_cases:[], expected_outputs:[])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new	
	end

	def create
		user = User.new(login_params)
		if user.valid?(:login)
			authenticate_user();
		else
			flash[:errors] = user.errors.full_messages
			redirect_to new_session_path
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to new_session_path
	end

	private
	def login_params
		params.permit(:email, :password)
	end

	def authenticate_user()
		user = User.find_by(email: params[:email])
		unless user.nil?
			if user && user.authenticate(params[:password])
				session[:user_id] = user.id
				redirect_to "/"
			else
				flash[:errors] = "Wrong password"
				redirect_to new_session_path
			end
		else
			flash[:errors] = "User does not exist"
			redirect_to new_session_path
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :check_user, except: [:new, :create]

	def new
	end

	def edit
	end

	def update
		user = current_user
		user.update(registration_params)
		if user.valid?
			redirect_to "/"
		else
			flash[:errors] = user.errors.full_messages
			redirect_to edit_user_path(current_user)
		end
	end
	
	def create
		user = User.create(registration_params)
		if user.valid?
			session[:user_id] = user.id
			redirect_to "/"
		else
			flash[:errors] = user.errors.full_messages;
			redirect_to new_user_path
		end
	end

	def user_puzzles
		@user_puzzles = current_user.puzzles
		render "brew_puzzles"
	end

	private
	def registration_params
		params.permit(:username, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/puzzle_forums_helper.rb
module PuzzleForumsHelper
end

app/helpers/puzzles_helper.rb
module PuzzlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Code Brew</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
	<%= javascript_importmap_tags %>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
	<%= include_gon(:init => true) %>
    <%= Gon::Base.render_data({}) %>
</head>
<body>
<% 	if current_user %>
<nav class="navbar navbar-expand-md navbar-light bg-light .text-bg-light">
	<div class="container-fluid">
		<div class="collapse navbar-collapse">
			<h1 id="logo" class="navbar-brand mt-2 mt-lg-0"><%= link_to "Code Brew", "/" %></h1>
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<li class="nav-item">
					<%= link_to "Puzzles", "/", class: "nav-link" %>
				</li>
				<li class="nav-item">
					<%= link_to "Brew Puzzle", brew_puzzles_path, class: "nav-link" %>
				</li>
			</ul>
		</div>
		<!-- Centered username -->
		<ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
			<li id="user" class="nav-item ">
				<%= link_to current_user.username, edit_user_path(current_user), class: "nav-link" %>
			</li>
			<li class="nav-item">
				<%= button_to 'Log out', session_path(current_user), method: :delete, class: "btn btn-dark" %>
			</li>
		</ul>
	</div>
</nav>
<%	end %>

<%	if flash[:errors] %>
	<div class="alert alert-danger text-center" role="alert">
<%		if flash[:errors].is_a?(String) %>
			<%= flash[:errors] %>
<%		else
			flash[:errors].each do |e|
%>				<%= e %>
<%			end
		end
%>	</div>
<%	end
%>	
    <%= yield %>
  </body>
</html>

app/views/puzzles/edit.html.erb
<%= form_with model: @puzzle, url: puzzle_path(@puzzle), method: :patch, class:"puzzle_form" do |f| %>
	<div class="text-center">
		<h2>Brew Puzzle</h2>
	</div>

	<div class="form-outline mb-4">
		<%= f.label :title, "Puzzle title", class:"form-label"%>
		<%= f.text_field :title, class:"form-control" %>
	</div>

	<div class="form-outline mb-4">
		<%= f.label :difficulty, "Difficulty", class:"form-label" %>
		<%= f.select :difficulty, options_for_select(@difficulty)%>
	</div>

	<div class="form-outline mb-4">
		<%= f.label :description, "Description", class:"form-label" %>
		<%= f.text_area :description, class:"form-control" %>
	</div>

	<div class="form-outline mb-4">
		<%= f.label :function, "Function name and parameters, Ex: sum(num1, num2)", class:"form-label" %>
		<%= f.text_field :function, class:"form-control" %>
	</div>

	<% 3.times do |index| %>
		<div id="test-cases" class="form-outline mb-4 border float-end">
			<p>Test case # <%= index+1 %></p>
			<div class="form-outline mb-2">
			<%= f.label :"test_cases", "Test case. Your test case for the created function, Ex: sum(1,2)" %>
			<%= f.text_field :"test_cases",multiple: true, value: @puzzle.test_cases[index],class:"form-control" %>
			</div>

			<div class="form-outline">
			<%= f.label :"expected_outputs", "Expected Output of test case, Ex: 3 (based on sum(1,2))" %>
			<%= f.text_field :"expected_outputs",multiple: true, value: @puzzle.expected_outputs[index], class:"form-control" %>
			</div>
		</div>
	<% end %>

	<%= f.submit "Brew!", class: "btn btn-dark btn-block mb-4"%>
<% end %>

app/views/puzzles/index.html.erb
<main id="index">
	<table class="table">
		<thead>
			<th scope="col">Puzzle</th>
			<th scope="col" class="text-center">Difficulty</th>
			<th scope="col" class="text-center">Creator</th>
			<th scope="col" class="text-center">Completed</th>
		</thead>
		<tbody>
		<% @puzzles.each do |puzzle| %>
			<tr>
				<td scope="row"><%= link_to puzzle.title, puzzle_path(puzzle.id) %>
				<td class="text-center"><%= puzzle.difficulty %></td>
				<td class="text-center"><%= puzzle.user.username %></td>
				<td class="text-center">
					<%= "&#10003;".html_safe if @user_puzzles[puzzle.id] %>
				</td>
			</tr>
		<% end %>
		</tbody>
	</table>
</main>

app/views/puzzles/new.html.erb
<%= form_with model: @puzzle, url: puzzles_path(@puzzle), class:"puzzle_form" do |f| %>
	<div class="text-center">
		<h2>Brew Puzzle</h2>
	</div>

	<div class="form-outline mb-4">
		<%= f.label :title, "Puzzle title", class:"form-label"%>
		<%= f.text_field :title, class:"form-control" %>
	</div>

	<div class="form-outline mb-4">
		<%= f.label :difficulty, "Difficulty", class:"form-label" %>
		<%= f.select :difficulty, options_for_select(@difficulty)%>
	</div>

	<div class="form-outline mb-4">
		<%= f.label :description, "Description", class:"form-label" %>
		<%= f.text_area :description, class:"form-control" %>
	</div>

	<div class="form-outline mb-4">
		<%= f.label :function, "Function name and parameters, Ex: sum(num1, num2)", class:"form-label" %>
		<%= f.text_field :function, class:"form-control" %>
	</div>

	<% 3.times do |index| %>
		<div id="test-cases" class="form-outline mb-4 border float-end">
			<p>Test case # <%= index+1 %></p>
			<div class="form-outline mb-2">
			<%= f.label :"test_cases", "Test case. Your test case for the created function, Ex: sum(1,2)" %>
			<%= f.text_field :"test_cases",multiple: true, class:"form-control" %>
			</div>

			<div class="form-outline">
			<%= f.label :"expected_outputs", "Expected Output of test case, Ex: 3 (based on sum(1,2))" %>
			<%= f.text_field :"expected_outputs",multiple: true, class:"form-control" %>
			</div>
		</div>
	<% end %>

	<%= f.submit "Brew!", class: "btn btn-dark btn-block mb-4"%>
<% end %>

app/views/puzzles/partials/_playback.html.erb
<tr>
	<td scope="row"><%= "#{@completed_puzzle.user.username}" %></td>
	<td><button type="button" class="btn btn-secondary" onClick="play(<%= @completed_puzzle.id-1 %>)">Watch</button></td>
<tr>

app/views/puzzles/partials/_post.html.erb
<div class="post_wrapper">
	<p class="post_username"><%= @post.user.username %></p>
	<p class="post_date"><%= @post.created_at.strftime("%m/%d/%Y")%></p>
	<%= form_with model: @new_post, url: edit_puzzle_forum_path(@puzzle.id,@post.id),method: :patch, class: "edit_post" do |f| %>
		<%= f.text_area :content, value: @post.content, class: "input-group post_content", disabled: true %>
	<% end %>
	<p class="fail"></p>
	<%= link_to "edit", edit_puzzle_forum_path(@puzzle.id,@post.id), class: "edit_post" %>
	<%= link_to "delete", puzzle_forum_path(@puzzle.id,@post.id),method: :delete, data: {turboost: :delete}, class: "delete_post" %>
</div>

app/views/puzzles/show.html.erb
<%= javascript_include_tag "puzzles" %>
<main id="puzzle" class="container-fluid">
	<div class="row">
		<div id="problem_info" class="col-md-4 border">
			<div>
				<ul class="nav nav-tabs">
					<li class="nav-item"><a data-toggle="tab" href="#home" class="nav-link">Puzzle</a></li>
					<li class="nav-item"><a data-toggle="tab" href="#discussion" class="nav-link">Discussion</a></li>
					<li class="nav-item"><a data-toggle="tab" href="#solutions" class="nav-link">Solutions</a></li>
				</ul>
			</div>

			<div class="tab-content">
				<div id="home" class="tab-pane fade in active">
					<h3><%= @puzzle.title %></h3>
					<p><%= @puzzle.description %></p>
				</div>
				<div id="discussion" class="tab-pane fade">
					<div>
						<h3>Discussion for <%= @puzzle.title %></h3>
						<%= form_with model:@new_post, url: puzzle_forums_path(@puzzle.id), id: "post" do |f|%>
							<div class="form-group">
								<%= f.text_area :content, placeholder: "Post a comment", class: "input-group", id:"new_post"%>
								<p id="post_errors" class="fail"></p>
							</div>
							<div class="form-group">
								<%= f.submit "Post", class: "btn btn-primary btn-block" %>
							</div>
						<% end %>
					</div>
					<div id="posts">
					<%	if @puzzle_posts
						@puzzle_posts.each do |post| %>
						<div class="post_wrapper">
							<p class="post_username"><%= post.user.username %></p>
							<p class="post_date"><%= post.created_at.strftime("%m/%d/%Y")%></p>
							<%= form_with model: @new_post, url: puzzle_forum_path(@puzzle.id,post.id), class: "edit_post", method: :patch do |f| %>
								<%= f.text_area :content, value: post.content, class: "input-group post_content", disabled: true %>
							<% end %>
							<p class="fail"></p>
							<%= link_to "edit", edit_puzzle_forum_path(@puzzle.id,post.id), class: "edit_post" %>
							<%= link_to "delete", puzzle_forum_path(@puzzle.id,post.id),method: :delete, data: {turboost: :delete}, class: "delete_post" %>
						</div>
					<% end 
					end %>
					</div>
				</div>
				<div id="solutions" class="tab-pane fade">
					<h3>Replays for completed <%= @puzzle.title %></h3>
					<table class="table">
						<thead>
							<th scope="col">User Name</th>
							<th scope="col">Replay</th>
						</thead>
						<tbody id="playbacks">
						<% @completed_puzzles.each do |completed_puzzle| %>
							<tr>
								<td scope="row"><%= "#{completed_puzzle.user.username}" %></td>
								<td><button type="button" class="btn btn-secondary" onClick="play(<%= completed_puzzle.id-1 %>)">Watch</button></td>
							<tr>
						<% end %>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div id="wrapper" class="col-md-8">
			<div id="code_wrapper">
				<p class="method">def <span id="method-name"><%= @puzzle.function %></p>
				<div id="code_area">
				</div>
				<p class="method" >end</p>
			</div>
			<form action="<%= validate_puzzle_path(@puzzle.id)%>" method="post" id="user_input">
				<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
				<input type="hidden" id="code" name="code">
				<input type="hidden" id="code" name="playback">
				<input type="submit" class="btn btn-dark btn-block">
			</form>
			<div id="console" class="border">
			<p id="console-errors"></p>
			<% for i in 0..2 %>
				<p id="case<%=i%>"><%=@puzzle.test_cases[i]%> should return <%=@puzzle.expected_outputs[i]%>
				<p id="case<%=i%>-console"></p>			
			<% end %>
			</div>
		</div>
	</div>
</main>

app/views/users/brew_puzzles.html.erb
<main id="index">
	<%= link_to "Create new puzzle", new_puzzle_path, class:"btn btn-dark"%>
	<table class="table">
		<h3><%=current_user.username%>'s Puzzles</h3>
		<table class="table">
			<thead>
				<th scope="col">Puzzle</th>
				<th scope="col">Difficulty</th>
				<th scope="col">Actions</th>
			</thead>
			<tbody>
			<% @user_puzzles.each do |puzzle| %>
				<tr>
					<td scope="row"><%= link_to puzzle.title, puzzle_path(puzzle.id) %>
					<td><%= puzzle.difficulty %></td>
					<td><%= link_to "Edit", edit_puzzle_path(puzzle) %> || <%= link_to "Delete", puzzle_path(puzzle), data: { turbo: true, turbo_method: :delete }, method: :delete %></td>
				</tr>
			<% end %>
			</tbody>
		</table>
	<table>
</main>

app/views/users/edit.html.erb
<form class="user_form" action="<%= user_path(current_user) %>" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<input type="hidden" name="_method" value="patch">
	<div class="text-center">
		<h1>Code Brew</h1>
		<h2>User details</h2>
	</div>

	<div class="form-outline mb-4">
		<label class="form-label" for="username">Username</label>
		<input type="text" id="username" name="username" value="<%= current_user.username %>" class="form-control">
	</div>

	<div class="form-outline mb-4">
		<label class="form-label" for="email">Email</label>
		<input type="email" id="email" name="email" value="<%= current_user.email %>" class="form-control">
	</div>

	<div class="form-outline mb-4">
		<label class="form-label" for="password">Password</label>
		<input type="password" id="password" name="password" class="form-control">
	</div>

	<div class="form-outline mb-4">
		<label class="form-label" for="password_confirmation">Confirm Password</label>
		<input type="password" id="password_confirmation" name="password_confirmation" class="form-control">
	</div>

	<input type="submit" class="btn btn-primary btn-block mb-4" value="Update">
</form>

app/views/users/new.html.erb
<form class="user_form" action="<%= users_path %>" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<div class="text-center">
		<h1>Code Brew</h1>
		<h2>Registration</h2>
	</div>

	<div class="form-outline mb-4">
		<label class="form-label" for="username">Username</label>
		<input type="text" id="username" name="username" class="form-control">
	</div>

	<div class="form-outline mb-4">
		<label class="form-label" for="email">Email</label>
		<input type="email" id="email" name="email" class="form-control">
	</div>

	<div class="form-outline mb-4">
		<label class="form-label" for="password">Password</label>
		<input type="password" id="password" name="password" class="form-control">
	</div>

	<div class="form-outline mb-4">
		<label class="form-label" for="password_confirmation">Confirm Password</label>
		<input type="password" id="password_confirmation" name="password_confirmation" class="form-control">
	</div>

	<input type="submit" class="btn btn-primary btn-block mb-4" value="Register">

	<div class="text-center">
		<p>Allready a member? <a href="<%= new_session_path %>">Login</a></p>
	</div>
</form>